name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # 或你的默认分支
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 只拉取最新 commit
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: arknights-resource  # 改成你的项目名
          directory: .  # 部署根目录所有文件
          gitHubToken: ${{ secrets.MY_TOKEN }}
